name: Feature Request
description: Suggest an idea or enhancement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement!

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem are you trying to solve?
      placeholder: I’m always frustrated when…
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: What would you like to happen?
      placeholder: I would like…
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Any alternative solutions or workarounds?
    validations:
      required: false

